### ISSUE TITLE
Perhaps use https://dash.upwork.com instead?

### ISSUE THREAD

**Issue by bieh** [Tribex/franz-recipe-upwork#1]
https://dash.upwork.com might be better -- that's actually the URL the Upwork app uses for the dedicated messaging window. That way you don't have the rest of the Upwork UI in there too. 

I made a little Upwork plugin for Franz3 myself a while back that used that URL, it worked pretty well.

**Comment by JoshTheDerf** [comment]
@bieh Ah, I was not aware of that! Thanks!

**Comment by bieh** [comment]
No problem :)
